# Generated by Django 5.1.7 on 2025-03-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
