# Generated by Django 5.1.7 on 2025-03-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_currency_options_alter_currency_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="value",
            field=models.FloatField(),
        ),
    ]
